### PR TITLE
add medication list

### LINKED ISSUE #75: Form element for blood types
We need a dropdown selection for the blood types below. This input should also be integrated into our patient data form as an optional field.

The rhesus factor is the + or - at the end of the blood group. The last four options are only blood groups without the rhesus factor, in case this information is not available. In the background, the select should output a structure where the blood group and rhesus factor is seperate.

- Blood types
  - A+
  - A-
  - B+
  - B-
  - AB+
  - AB-
  - O+
  - O-
  - A
  - B
  - AB
  - O

### LINKED ISSUE #77: Form element for current medications
This input should gather the current medication of the patient. In long-term we want to build up a database with medications and doses of these. This means, this should be a dropdown with many possible options of types of medications and another one for the doses (like "every day", "every six hours" for example).

This input should also be a port of #72 and will also be optional.

### PR DESCRIPTION
**Pull request by DasProffi**
closes #77

### CODE REVIEW

**Comment by DasProffi** [comment]
minmized
expanded
search_results
search_no_hit

**Comment by DasProffi** [comment]
updated design
design_change

**Comment by DasProffi** [comment]
updated paddings in emergency pass
desing_with_updated_padding

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
Looks good, I also like the ability to add custom medications. In the future, I can imagine that we can send back these custom medications to our backend, and add them to our database.

Two issues:
- [ ] We should add a bug button to the medication search
- [ ] Similar bug as #86. How can I help to track down these issues?
Bildschirmfoto 2022-12-26 um 2 37 35 PM

**Comment by DasProffi** [comment]
Choice 1, easy to report and identify a single wrong tile:
rport on tile
Choice 2 (currently implemented) harder to report and identify a single wrong tile, but looks better and seems less confusing for user experience:
report in appbar
Width constraint for dosage selection:
Unbenannt

**Comment by MaxSchaefer** [comment]
Okay, shit. I mean "back"-button, not "bug"-button. Sorry for that typo :D

**Comment by MaxSchaefer** [comment]
But a "bug"-Button seams, like a nice feature for the future. Right now, there are just wrong names that can be reported.

**Comment by DasProffi** [comment]
redesign:
backbutton

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
