### PR TITLE
add landing-page

### LINKED ISSUE #5: landing page
The landing page will be the very first page to serve.
Just show a splash screen for now.

### PR DESCRIPTION
**Pull request by DasProffi**
This pull request adds the landing-page and a basic customizable theme

closes #5 

Testing instructions:
- open the app

### CODE REVIEW

**Comment by Florian-Sabonchi** [comment]
Thats a nice draft, but wie wait until mockups ready

**Comment by DasProffi** [comment]
"Just show a splash screen for now." see #5
this commit also includes a basic colorsheme and thereby has additional value for the main branch

**Review by use-to — APPROVED** [review]

**Comment by use-to** [comment]
Looks good! You can use @frontend the next time to request reviewers.

**Comment by use-to** [comment]
@Florian-Sabonchi no the issue is quite clear here.

**Review by MaxSchaefer — APPROVED** [review]

**Pull request merged**
