### PR TITLE
task creation edit

### LINKED ISSUE #181: Task Creation/Edit
Screen to edit/create a Task.

See #195 for some helpful code snippets

Wait for design before implementation

### PR DESCRIPTION
**Pull request by DasProffi**
closes #181
Capture
Capture2

### CODE REVIEW

**Comment by DasProffi** [comment]
Updated alignment
Capture

**Comment by DasProffi** [comment]
Capture

**Comment by use-to** [comment]
Please provide a proper navigation to the implemented screen.

**Comment by DasProffi** [comment]
Due to the rework of the design, this PR will be closed

**Pull request closed without merging**
