### PR TITLE
show landing page only once

### LINKED ISSUE #115: show LandingPage only once
Currently the landing page is displayed on every start of the app, which is interrupting the ux

- implement a model and shared preferences as for light mode and set a flag whether the landing page was seen
  - only set the flag once the start button is pressed
- See `ThemeModel` and `ThemePreferences` for a reference

### PR DESCRIPTION
**Pull request by DasProffi**
closes #115

### CODE REVIEW

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
We should give the user the ability to reset their introduction state via the settings. Can you add this?

**Comment by DasProffi** [comment]
Capture
Capture2

**Comment by MaxSchaefer** [comment]
> @MaxSchaefer is that okay or would you rather have a ListTile which redirects to the Landing page?

I think we should use a verbose ListTile. For now the button should only reset the intro screen. The text should be something like "Reset intro"/"Intro zurücksetzten".

**Comment by florian-sabonchi** [comment]
Hi, i would suggest to follow current design so we shoud use listtile

**Comment by DasProffi** [comment]
Capture
Capture2

**Review by MaxSchaefer — APPROVED** [review]

**Comment by MaxSchaefer** [comment]
Nice, thanks 🎉

**Pull request merged**
