### PR TITLE
chore: build apk on pushing tag and create release

### PR DESCRIPTION
**Pull request by florian-sabonchi**

### CODE REVIEW

**Comment by florian-sabonchi** [comment]
Should be checked by our CI/CD expert @use-to 
todo: signing the apks through the pipeline

**Review by MaxSchaefer — COMMENTED** [review]
We should do the build and release of the apk as a part of https://github.com/helpwave/mobile-app/blob/main/.github/workflows/ci.yaml. In the future, #104 should integrate with the build step. If we distribute the build into different workflows, we need to lint there as well, etc.

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]
_Conversation moved here from the [comment above](https://github.com/helpwave/mobile-app/pull/105#pullrequestreview-1236301433)_

**Comment by use-to** [comment]
This pr is on the bottom of my stack atm. Cause we need to figure out a way how to build, deliver and deploy the app (and also the microservices) in a secure and monitored way. I'll come back later on...

**Comment by MaxSchaefer** [comment]
Included with #122

**Pull request closed without merging**
