### PR TITLE
add app icon

### PR DESCRIPTION
**Pull request by Florian-Sabonchi**
feat: add app icon for ios and android @MaxSchaefer please approve on ios

### CODE REVIEW

**Review by DasProffi — CHANGES_REQUESTED** [review]
The Icon in the Taskmanager is still the old flutter icon and the background color of the launcher icon should be set to our background color "#1B1B1B"

**Comment by DasProffi** [comment]
Capture

**Comment by Florian-Sabonchi** [comment]
Screenshot_20221023-225817

Coud be a issue with your device

**Comment by Florian-Sabonchi** [comment]
Tomorrow i will look in the Background color

**Comment by use-to** [comment]
> Tomorrow i will look in the Background color
don't let yourself be blinded

**Comment by Florian-Sabonchi** [comment]
> > Tomorrow i will look in the Background color
> 
> don't let yourself be blinded

Closed with #41

**Pull request closed without merging**
