### PR TITLE
add generalized content selection

### LINKED ISSUE #89: Generalize content selector with build-in search
This feature was introduced with #83. In #85 we realized that we can use this feature as well. This issue should handle the abstraction of this list to be used in the medication and allergies list, and should be future-proof as well.
Requirements (retrieved from the current state of the medication selector):
- Dropdown header with icon and amount of content
- Dropdown body with a list of the content and the ability to remove entries
- Every entry in the dropdown body should also have some unique options
  - Like doses for medications
- To add more entries / content, the last option should be an add-button that navigates the user to a search
- The search should hold the data that can be added. Hard-coded in the app or can be retrieved via our backend.
- When something is not in that list (predefined entry), the generalized version should have a config that allows a developer to add not predefined entries (custom entry) back to the entries listing in the dropdown body

### PR DESCRIPTION
**Pull request by DasProffi**
closes #89 

Test Instructions:
- Test this the code below and add additional parameteres as you like.
```
ContentSelector(
  title: "Weather Stations",
  icon: Icon(Icons.ac_unit),
  selectionItems: [{"weather": "cold"},{"weather": "warm"}, {"weather": "hot"}],
  onChangedList: print,
  valueToString: (value) => value["weather"]!,
  equalityCheck: (value1, value2) => value1["weather"] == value2["weather"],
  loadAsyncSearchOptions: (searched, ignoreList) async {
    String searchInLower = searched.toLowerCase();
    List  <String> result = [];
    List  <String> filteredSearchOptions = ["Louisiana","New York","Tokyo","Berlin"];
    filteredSearchOptions
      .retainWhere((element) => !ignoreList.contains(element));
    for (var element in filteredSearchOptions) {
      if (!filteredSearchOptions.contains(searched) &&
          element.toLowerCase().startsWith(searchInLower)) {
        result.add(element);
      }
    }
    return result;
  },
),
```

Updated wrong code example

### CODE REVIEW

**Comment by DasProffi** [comment]
expanded
search

**Comment by MaxSchaefer** [comment]
The following error occurred when I add `selectionDefaultValue: {"weather": "hot"},` to the test code.
Bildschirmfoto 2022-12-26 um 10 38 08 PM

**Comment by DasProffi** [comment]
> The following error occurred when I add `selectionDefaultValue: {"weather": "hot"},` 
The map == operator in the native DropDownButton was causing issues, it seems like its checking by reference, so I added a equlity check (visible in the updated test code). This resolves the issue by finding the equal object in the items list and thereby the reference problem.
For primitive types like string, int or enums this shouldn't be necessary.

**Comment by MaxSchaefer** [comment]
> > The following error occurred when I add `selectionDefaultValue: {"weather": "hot"},`
> 
> The map == operator used in the native DropDownButton was causing issues, it seems like its checking by reference, so I added a equlity check (visible in the updated test code). This resolves the issue by finding the equal object in the items list and thereby the reference problem. For primitive types like string, int or enums this shouldn't be necessary.

Okay nice, now it works. Thank you.

Can @use-to or @florian-sabonchi take a glance at the dart code?

**Comment by florian-sabonchi** [comment]
image
The desing we should reconsider I find the text here does not quite fit

**Comment by DasProffi** [comment]
> The desing we should reconsider I find the text here does not quite fit

That part doesn't belong to the issue, only the screenshot above
expanded
search

**Review by MaxSchaefer — APPROVED** [review]
Approved from a usability / DX point of view!

**Pull request merged**
