### PR TITLE
fix too long notifyCancel text

### LINKED ISSUE #58: Text of `notifyCancel`-Button overflows
Simulator Screen Shot - iPhone 14 Pro - 2022-11-06 at 12 09 08

### PR DESCRIPTION
**Pull request by DasProffi**
closes #58
Capture

### CODE REVIEW

**Review by use-to — CHANGES_REQUESTED** [review]
I feel like this is not a sufficient solution.
Maybe we should design the button to able to overflow in all directions.
What do you think?

**Comment by DasProffi** [comment]
I agree that this doesn't feel like a sufficient, but maybe we want to navigate to another page once the user clicks notify.
The Navigation would make sense from a ux point of view.

**Comment by DasProffi** [comment]
And a button that is allowed to overflow isn't a very nice solution either.
- multi line buttons are not very nice
- diffrent sized buttons are also not pretty
- And just cutting or letting the button actually overflow aren't good solutions

Maybe you have some other idea?

**Comment by DasProffi** [comment]
Capture

**Comment by DasProffi** [comment]
Capture

**Review by use-to — APPROVED** [review]
Perfect!

**Pull request merged**
