### PR TITLE
add basic task bottom sheet

### LINKED ISSUE #350: Add  Bottom Sheet for task
### Describe the chore

grafik

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #350

### CODE REVIEW

**Comment by DasProffi** [comment]
This issue is too bloated and several subcomponents should be made from this.

- grpc for subtask list
- grpc for task with proper form handling (don't update on every character)
- fix modal corners by using material3 or an invisible modal background with a visible container within the modal

## Open questions
- Should Assignee, Due Date and Visibility also be changeable from this view?
- What is the purpose of the edit button? (readonly and edit view/only to change the title)
- Why is the patient name a drop-down?

@use-to @MaxSchaefer how do we want to handle this?

**Comment by use-to** [comment]
> This issue is too bloated and several subcomponents should be made from this.
> 
> * grpc for subtask list
> * grpc for task with proper form handling (don't update on every character)
> * fix modal corners by using material3 or an invisible modal background with a visible container within the modal
> 
> ## Open questions
> * Should Assignee, Due Date and Visibility also be changeable from this view?
> * What is the purpose of the edit button? (readonly and edit view/only to change the title)
> * Why is the patient name a drop-down?
> 
> @use-to @MaxSchaefer how do we want to handle this?

@helpwave/medical @helpwave/design or @jonas-ester

**Comment by DasProffi** [comment]
> ## Open questions
> * Should Assignee, Due Date and Visibility also be changeable from this view?

Yes
> * What is the purpose of the edit button? (readonly and edit view/only to change the title)

To edit the title, but should be removed as we adopt color coded edit fields
> * Why is the patient name a drop-down?

It shouldn't have been, so it isn't anymore and the chevron needs to be removed

**Comment by use-to** [comment]
@DasProffi What's the current status of this pr?

**Comment by DasProffi** [comment]
> @DasProffi What's the current status of this pr?

Main merged, Issues resolved and new Issues opened.
See:
#386
#387
#388
#389

**Comment by DasProffi** [comment]
@use-to your review

**Review by use-to — APPROVED** [review]
@DasProffi Good job! Nicely documented, and you clarified the screen design and create the issues the before.
I feel like some of the margins between these the icons and the corresponding value (date, assignee, visibility) are too low. Also, the text should be in space and the subtask checkboxes are too small and needs to be colored.

**Pull request merged**
