### PR TITLE
add allergies form to emergency pass

### LINKED ISSUE #76: Form element for allergies
Multi-Select with allergies. The backend should provide these values in the future.

### PR DESCRIPTION
**Pull request by DasProffi**
closes #76
empty
selection
selected

### CODE REVIEW

**Comment by MaxSchaefer** [comment]
@DasProffi I like the tag approach, but what do you think if we adopt the same UX as #83? That means:
- Dropdown button with icon, name and amount of content
- Dropdown box with specific content
- Search to add more predefined or custom content

The reuse of #83 should increase the UX.

**Comment by DasProffi** [comment]
Makes sense, then I would make a generalized version of this with a search list, but we should merge #83 before or create a separate issue for the generalized version

What category for allergy did you have in mind? Reaction Severity (light, medium, severe)?

**Comment by MaxSchaefer** [comment]
A generalized version would be nice. #83 is merged. Do you still want an issue for generalization? Would not be a problem.

**Comment by MaxSchaefer** [comment]
You can implement the ...
> Reaction Severity (light, medium, severe)

..., I will discuss the details of this with Christian.

**Comment by DasProffi** [comment]
> A generalized version would be nice. #83 is merged. Do you still want an issue for generalization? Would not be a problem.

Thinking in issue concerns/scopes, it would make sense to have a separate issue

**Comment by MaxSchaefer** [comment]
Okay, following plan:
- This pr gets into draft state until #89 is closed.
- When #89 is closed, the new generalized version gets implemented for the allergies.
- After that, we can implement the generalized version for the medicals.

**Comment by DasProffi** [comment]
dropdown
inPass
search

**Comment by DasProffi** [comment]
updated allergy search

**Review by MaxSchaefer — APPROVED** [review]

**Comment by DasProffi** [comment]
padding

**Pull request merged**
