### PR TITLE
add persistent patient data

### LINKED ISSUE #88: Persist patient data on device

### PR DESCRIPTION
**Pull request by DasProffi**
closes #88

### CODE REVIEW

**Review by florian-sabonchi — COMMENTED** [review]
From my point of view Singelton is an antipattern and therefore should not be used for this reason I would suggest that we all together should make a decision about it
https://stackoverflow.com/questions/12755539/why-is-singleton-considered-an-anti-pattern

**Comment by MaxSchaefer** [comment]
> From my point of view Singelton is an antipattern and therefore should not be used for this reason I would suggest that we all together should make a decision about it
> https://stackoverflow.com/questions/12755539/why-is-singleton-considered-an-anti-pattern

@florian-sabonchi if the code is functional, can we merge it and take it as a TOP to the next meeting?

**Comment by use-to** [comment]
Is this persistence working on ios?

**Comment by MaxSchaefer** [comment]
> Is this persistence working on ios?

Yes

**Review by use-to — APPROVED** [review]
in essence this is good. A big part of this code will change later on.

**Pull request merged**
